### ISSUE TITLE
planet.plone.org without CSS

### ISSUE THREAD

**Issue by macagua** [plone/planet.plone.org#59]
Hi guys

@keul report 3 days ago this issue https://github.com/plone/ploneorg.core/issues/149

"Not sure where planet.plone.org issues must be reported, but I fear that recent plone.org migration has broken the blog site.

http://planet.plone.org/

It seems that it's requesting for plone.org/plone.css that is now an empty resource"

In the same way I report a simple solution:

"If change the URL CSS link from:
```css
<link rel="stylesheet" href="http://plone.org/plone.css" type="text/css" media="screen" charset="utf-8">
```
To this new URL: 
```css
<link rel="stylesheet" href="http://old.plone.org/plone.css" type="text/css" media="screen" charset="utf-8">
```

This screenshot was made with my Weddev Inspect Tool:

![screenshot from 2016-05-15 20 08 33](https://cloud.githubusercontent.com/assets/185395/15277673/04edf5a4-1ad5-11e6-90d8-6d783fb4c0e8.png)

I can help with this minimal change, if assign to me this issue, but I can access to deploy this improvement."

**Comment by svx** [comment]
done, will be deployed with the next build
